id: P000352
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 2021-12-16 15:35:28.723818
source_metadata:
  id: bdr:W8722
  title: ཨ་བསེའི་བྱུང་ཁུངས་ལོ་རྒྱུས་མདོ་ཙམ་བརྗོད་པ
  author: ''
  volumes:
    db112e7fb59646e0b110d7ce072e4c76:
      image_group_id: I1GS105577
      title: Volume 1 of a bse'i byung khungs lo rgyus mdo tsam brjod pa
      volume_number: 1
      total_pages: 36
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
